name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]

permissions:
  actions: read
  contents: read
  statuses: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  SRC_DIR: src/github.com/${{ github.repository }}

jobs:
  Go:
    name: Go
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ '1.19.x', '1.20.x' ]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{env.SRC_DIR}}

      - name: Download dependencies
        working-directory: ${{env.SRC_DIR}}
        run: make deps

      - name: Build binary
        working-directory: ${{env.SRC_DIR}}
        run: make all

      - name: Do tests
        working-directory: ${{env.SRC_DIR}}
        run: |
          ./knfgen testdata/test1.source | sha1sum | grep -q 'dbfffea813d04de4d838f1877b54fc53cee73616'
          ./knfgen testdata/test2.source | sha1sum | grep -q 'dbfffea813d04de4d838f1877b54fc53cee73616'
